# Dockerfile.api
FROM python:3.11-slim
WORKDIR /app
ENV PYTHONPATH=/app
COPY app/requirements.txt .
RUN pip install --no-cache-dir --timeout=100 -r requirements.txt

COPY alembic.ini .
COPY alembic ./alembic
COPY app ./app
# Command to run the FastAPI server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]