# Dockerfile.worker
FROM python:3.11-slim
WORKDIR /app
ENV PYTHONPATH=/app
COPY app/requirements.txt .
RUN pip install --no-cache-dir --timeout=100 -r requirements.txt && pip install transformers

COPY app /app
WORKDIR /app/app
# Command to run the Celery worker
CMD ["celery", "-A", "tasks", "worker", "-l", "info"]